In [2]:
import numpy as np
a=np.array([1,2,0,7],dtype=bool)
print(a.dtype)
print(a)

bool
[ True  True False  True]


In [3]:
#more than one dimensions
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [4]:
#minimum dimension
a=np.array([1,2,3,7,9],ndmin=3)
print(a)

[[[1 2 3 7 9]]]


In [5]:
#dtype parameter
a=np.array([1,2,3],dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [104]:
#using array-scalar type
dt=np.dtype(np.int32)
print(dt)

int32


In [106]:
x=np.array([12])
print(x.dtype)

int32


In [8]:
x=np.array([12.20])
print(x.dtype)

float64


In [9]:
dt=np.dtype('i8')
print(dt)

int64


In [10]:
#ndarray.shape--to know row column
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [111]:
#this resize the ndarray
a=np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [113]:
#Numpy also provides a reshape function to resize an array
a=np.array([[1,2,3],[4,5,6]])
print(a)
b=a.reshape(3,2)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [116]:
x=np.zeros((4,3),dtype=int)
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [119]:
x=np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


In [15]:
x=np.ones([2,2],dtype=int)
print(x)

[[1 1]
 [1 1]]


In [120]:
#now reshape it
b=np.ones([4,12],dtype=int)
a=b.reshape(3,4,4)
print(a)
#b is having three dimesion

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [17]:
#numpy.empty
x=np.empty([3,4],dtype=int)
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [123]:
#identity matrix
x=np.eye((4),dtype=int)
print(x)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [19]:
#diagonal 
x=np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
a=np.diag(x)
a

array([ 0,  5, 10, 15])

In [21]:
x=np.array([12,54,76,89,43,32])
np.diag(x)

array([[12,  0,  0,  0,  0,  0],
       [ 0, 54,  0,  0,  0,  0],
       [ 0,  0, 76,  0,  0,  0],
       [ 0,  0,  0, 89,  0,  0],
       [ 0,  0,  0,  0, 43,  0],
       [ 0,  0,  0,  0,  0, 32]])

In [22]:
#arange method
import numpy as np
a=np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [125]:
#this is one dimentional array
a=np.arange(24)
a.ndim

1

In [24]:
x=np.arange(5,dtype=float)
print(x)

[0. 1. 2. 3. 4.]


In [25]:
#start and stop parameters set
x=np.arange(10,20,2)
print(x)

[10 12 14 16 18]


In [26]:
#linspace function
x=np.linspace(10,20,5)
print(x)

[10.  12.5 15.  17.5 20. ]


In [27]:
x=np.linspace(10,20,7)
print(x)

[10.         11.66666667 13.33333333 15.         16.66666667 18.33333333
 20.        ]


In [28]:
#endpoint set to false
x=np.linspace(10,20,5,endpoint=False,retstep=True)
print(x)

(array([10., 12., 14., 16., 18.]), 2.0)


In [29]:
#find retstep value
x=np.linspace(1,2,5,retstep=True)
print(x)

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)


In [30]:
#convert list to ndarray
x=[1,2,3]
print(type(x))
a=np.asarray(x)
print(type(a))
print(a)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3]


In [31]:
#dtype is provided
x=[1,2,3]
a=np.asarray(x,dtype=float)
print(a)

[1. 2. 3.]


In [32]:
#ndarray from tuple
x=(1,2,3)
a=np.asarray(x)
print(a)

[1 2 3]


In [33]:
#ndarray from list of tuple
x=[(1,2,3),(4,5,7)]
a=np.asarray(x)
print(a)

[[1 2 3]
 [4 5 7]]


In [34]:
#accessing
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [35]:
a[2:4]

array([3, 4])

In [36]:
a[1:4]

array([2, 3, 4])

In [37]:
a[1:]

array([2, 3, 4, 5])

In [38]:
a[:4]

array([1, 2, 3, 4])

In [39]:
a[::-1]

array([5, 4, 3, 2, 1])

In [40]:
a[-2:]

array([4, 5])

In [41]:
a[:-2]

array([1, 2, 3])

In [42]:
#create matrix in numpy
#create 2x2 matrix
matrix1=np.array([[1,3],[5,7]])
print('2x2 matrix:\n',matrix1)

2x2 matrix:
 [[1 3]
 [5 7]]


In [43]:
#create 3x3 matrix
matrix2=np.array([[2,3,5],[7,13,68],[3,7,9]])
print("\n3x3 Matrix:\n",matrix2)


3x3 Matrix:
 [[ 2  3  5]
 [ 7 13 68]
 [ 3  7  9]]


In [44]:
#sum of two matrix
matrix1=np.array([[4,6,2],[6,9,2],[2,1,9]])
print(matrix1)
print()
matrix2=np.array([[4,6,9],[1,7,43],[43,43,42]])
print(matrix2)
print()
s_m=matrix1+matrix2
print(s_m)

[[4 6 2]
 [6 9 2]
 [2 1 9]]

[[ 4  6  9]
 [ 1  7 43]
 [43 43 42]]

[[ 8 12 11]
 [ 7 16 45]
 [45 44 51]]


In [45]:
#perform matrix multiplication in numpy..we use the np.dot() function to perform multiplication b/w two matrics
import numpy as np
matrix1=np.array([[1,3],[5,7]])
matrix2=np.array([[2,6],[4,8]])
result=np.dot(matrix1,matrix2)
print("matrix1 x matrix2:\n",result)

matrix1 x matrix2:
 [[14 30]
 [38 86]]


In [46]:
#In numpy,we can obtain the transpose of a matrix using the np.transpose() fn.
matrix1=np.array([[1,3,5],[5,7,9]])
print(matrix1)
print()
result=np.transpose(matrix1)
print(result)

[[1 3 5]
 [5 7 9]]

[[1 5]
 [3 7]
 [5 9]]


In [47]:
#numpy.hstack() function--horizontally stack numpy arrays using numpy.hstack()
x=np.array((3,5,6))
print(x)
print()
y=np.array((6,7,8))
print(y)
print()
np.hstack((x,y))

[3 5 6]

[6 7 8]



array([3, 5, 6, 6, 7, 8])

In [48]:
x=np.array([[3],[5],[7]])
print(x)
print()
y=np.array([[5],[9],[2]])
print(y)
print()
np.hstack((x,y))

[[3]
 [5]
 [7]]

[[5]
 [9]
 [2]]



array([[3, 5],
       [5, 9],
       [7, 2]])

In [49]:
#np.vstack-vertically stack
x=np.array([3,6,8])
print(x)
print()
y=np.array([5,9,1])
print(y)
print()
np.vstack((x,y))

[3 6 8]

[5 9 1]



array([[3, 6, 8],
       [5, 9, 1]])

In [50]:
x=np.array([[3],[6],[8]])
print(x)
print()
y=np.array([[5],[9],[1]])
print(y)
print()
np.vstack((x,y))

[[3]
 [6]
 [8]]

[[5]
 [9]
 [1]]



array([[3],
       [6],
       [8],
       [5],
       [9],
       [1]])

In [51]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
x.ndim

2

In [53]:
x.shape

(3, 3)

In [54]:
x=np.array([[1,11,12,13],[2,23,7,28],[31,32,34,35],[41,42,5,44]])
print(x)

[[ 1 11 12 13]
 [ 2 23  7 28]
 [31 32 34 35]
 [41 42  5 44]]


In [55]:
print(x[1:3,1:3])

[[23  7]
 [32 34]]


In [56]:
print(x[1:3,:2])

[[ 2 23]
 [31 32]]


In [57]:
np.sort(x)

array([[ 1, 11, 12, 13],
       [ 2,  7, 23, 28],
       [31, 32, 34, 35],
       [ 5, 41, 42, 44]])

In [58]:
np.sort(x,axis=0)

array([[ 1, 11,  5, 13],
       [ 2, 23,  7, 28],
       [31, 32, 12, 35],
       [41, 42, 34, 44]])

In [59]:
ls=[23,56,21,98,34,89]
b=np.array(ls)
print(b)

[23 56 21 98 34 89]


In [60]:
b.argmax()

3

In [61]:
b.argsort()

array([2, 0, 4, 1, 5, 3], dtype=int64)

In [62]:
b[b.argsort()]

array([21, 23, 34, 56, 89, 98])

In [128]:
#conditional selection
import numpy as np
a=np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [129]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [130]:
a[a>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [131]:
a[a<10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [133]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [134]:
a[a<5]

array([1, 2, 3, 4])

In [135]:
a[a==5]

array([5])

In [138]:
a[a%2!=0]=0

In [139]:
a

array([ 0,  2,  0,  4,  0,  6,  0,  8,  0, 10,  0, 12,  0, 14,  0, 16,  0,
       18,  0, 20])

In [73]:
#where function
a=np.array([1,2,3,4,5,2])
print(a)

[1 2 3 4 5 2]


In [74]:
a.ndim

1

In [75]:
a.shape

(6,)

In [76]:
np.where(a==2)

(array([1, 5], dtype=int64),)

In [142]:
#searchsorted
x=np.array([1,2,3,4,10,11,15])
print(x)

[ 1  2  3  4 10 11 15]


In [143]:
np.searchsorted(x,8)

4

In [145]:
np.searchsorted(x,16)

7

In [80]:
#comparision b/w list and array
#takes less momory
import time
import sys

In [148]:
sys.getsizeof(1000)

28

In [82]:
l=range(200000)
print(sys.getsizeof(2)*len(l))

5600000


In [83]:
a=np.arange(200000)
a.itemsize

4

In [84]:
a=np.arange(200000)
print(a.itemsize*len(a))

800000


In [85]:
a1=range(1000000)
b1=range(1000000)

start=time.time()
c1=[(x+y) for x,y in zip(a1,b1)]
print("time taken:",(time.time()-start)*1000)

time taken: 249.76205825805664


In [86]:
time.time()*1000

1717917721498.208

In [152]:
#fast
a2=np.arange(1000000)
b2=np.arange(1000000)
start=time.time()
c2=a2+b2
print("time taken by:",(time.time()-start)*1000)

time taken by: 2.0110607147216797


In [151]:
#convinient
n1=np.arange(10)
n2=np.arange(10)


In [89]:
n1*n2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [90]:
#shallow copy
ls=[12,23,54,32,76,14]
ls1=ls.copy()
print(ls)
print(ls1)
ls1[3]="Nishant"
print(ls)
print(ls1)

[12, 23, 54, 32, 76, 14]
[12, 23, 54, 32, 76, 14]
[12, 23, 54, 32, 76, 14]
[12, 23, 54, 'Nishant', 76, 14]


In [91]:
ls=[[12,23,54],[32,76,14]]
ls1=ls.copy()
print(ls)
print(ls1)
ls1[0][2]="Nishant"
print(ls)
print(ls1)

[[12, 23, 54], [32, 76, 14]]
[[12, 23, 54], [32, 76, 14]]
[[12, 23, 'Nishant'], [32, 76, 14]]
[[12, 23, 'Nishant'], [32, 76, 14]]


In [92]:
import copy
ls=[[12,23,54],[32,76,14]]
ls1=copy.deepcopy(ls)
print(ls)
print(ls1)
ls1[0][2]="Nishant"
print(ls)
print(ls1)

[[12, 23, 54], [32, 76, 14]]
[[12, 23, 54], [32, 76, 14]]
[[12, 23, 54], [32, 76, 14]]
[[12, 23, 'Nishant'], [32, 76, 14]]


In [178]:
#generate random integer from 0 to 9
import numpy as np
random_number=np.random.randint(1,7)
print(random_number)

3


In [179]:
#note-we can also import and use the random module like this:
from numpy import random
random_number=random.randint(0,10)
print(random_number)

5


In [194]:
#generate ramdom float in Numpy
#float point number b/w 0 and 1
random_number=np.random.rand()
print(random_number)


0.31441695042923645


In [189]:
#generate 1D array of 5 random integers b/w 0 and 9
integer_array=np.random.randint(0,10,4)
print("1D random integer array:\n",integer_array)

1D random integer array:
 [0 7 2 3]


In [198]:
#generate 1D array of 5 random numbers b/w 0 and 1
float_array=np.random.rand(5)
print("\n1D random float_array:\n",float_array)


1D random float_array:
 [0.92771357 0.38659638 0.46212547 0.57862899 0.1139206 ]


In [204]:
#generate 2D array of shape (3,4) with random integers
result=np.random.randint(0,10,(3,4))
print("\n2D random integer array:\n",result)


2D random integer array:
 [[8 6 5 0]
 [0 5 1 3]
 [2 3 1 0]]


In [210]:
#create an array of integers from 1 to 5
array1=np.array([1,2,3,4,5])
print(array1)
#choose a random number from array1
random_choice=np.random.choice(array1)
print(random_choice)


[1 2 3 4 5]
3


In [218]:
import numpy as np
from numpy.random import randint as ri


In [220]:
np.random.seed(100)
ri(1,100,(5,6))

array([[ 9, 25, 68, 88, 80, 49],
       [11, 95, 53, 99, 54, 67],
       [99, 15, 35, 25, 16, 61],
       [59, 17, 10, 94, 87,  3],
       [28,  5, 32,  2, 14, 84]])

In [102]:
#numpy complete!